#!/bin/bash

LOCALDIR=`cd "$( dirname $0 )" && pwd`
cd $LOCALDIR

systemdir=$1

apps_dir="
com.miui.face
vendor.qti.imsrcs
com.qualcomm.qti.ims
org.codeaurora.ims
com.android.carrierconfig
com.qualcomm.qcrilmsgtunnel
com.miui.cit
com.miui.personalassistant
com.android.se
com.miui.audiomonitor
GMS
Google
com.android.vending
Google
com.google.android.onetimeinitializer
Google
com.android.calllogbackup
Google 服务框架
com.google.android.gsf
com.android.printspooler
com.android.bips
com.google.android.printservice.recommendation
游戏服务 
com.xiaomi.gamecenter.sdk.service
com.xiaomi.migameservice
com.xiaomi.macro
com.xiaomi.barrage
com.android.simappdialog
com.qualcomm.qti.autoregistration
com.qualcomm.qti.simcontacts
com.android.carrierdefaultapp
com.xiaomi.aiasst.service
com.mipay.wallet
com.xiaomi.pass
com.xiaomi.payment
com.miui.nextpay
Joyose 
com.xiaomi.joyose
com.xiaomi.mi_connect_service
com.miui.mishare.connectivity
com.xiaomi.mirror
com.xiaomi.miplay_client
com.miui.yellowpage
com.miui.cloudservice.sysbase
com.android.backupconfirm
com.android.quicksearchbox
com.miui.touchassistant
com.miui.systemAdSolution
com.miui.daemon
com.miui.hybrid
com.miui.carlink
com.android.dreams.phototable
com.android.dreams.basic
com.android.wallpaperbackup
com.android.wallpaper.livepicker
com.android.wallpapercropper
WMService 
com.miui.wmsvc
FIDO UAF1.0 Client 
com.fido.xiaomi.uafclient
FIDO UAF1.0 ASM 
com.fido.asm
com.android.protips
com.android.stk
com.miui.miservice
com.android.provision
com.miui.translation.kingsoft
com.android.pacprocessor
com.xiaomi.security.onetrack 
com.miui.bugreport
com.unionpay.tsmservice.mi
com.xiaomi.ab
Mi RCS 
com.xiaomi.mircs
com.miui.hybrid.accessory
com.xiaomi.mtb
com.xiaomi.cameratools
com.wapi.wapicertmanage
Wfd Service 
com.qualcomm.wfd.service
MediaFeature
com.miui.mediafeature
Call Log Backup/Restore 
com.android.calllogbackup
com.android.providers.userdictionary
com.google.android.marvin.talkback
com.miui.accessibility
com.miui.translation.youdao
com.android.bookmarkprovider
com.miui.maintenancemode
com.miui.translationservice
com.miui.vsimcore
com.miuix.editor
com.xiaomi.otrpbroker
com.xiaomi.xmsfkeeper
com.xiaomi.miaudiovisual
com.android.providers.media
com.qualcomm.qti.ridemodeaudio
com.miui.audioeffect
com.android.soundpicker
com.miui.vipservice
com.qti.diagservices
com.android.statementservice
com.android.traceur
com.android.managedprovisioning
com.qti.ltebc
dpm
com.qti.dpmserviceapp
com.qualcomm.qti.workloadclassifier
com.qti.qualcomm.mstatssystemservice
com.android.localtransport
com.qualcomm.qti.devicestatisticsservice
com.android.networkstack.permissionconfig
com.qualcomm.qti.poweroffalarm
com.qti.qualcomm.deviceinfo
com.google.android.tag
com.android.cellbroadcastreceiver
com.android.cellbroadcastservice
com.android.inputdevices
SystemHelper
com.mobiletools.systemhelper
X-Divert设置
com.qti.xdivert
ONS
com.android.ons
com.android.certinstaller
System_Helper_Service
com.qualcomm.qti.services.systemhelper
ProxyHandler
com.android.proxyhandler
QColor 
com.qualcomm.qti.qcolor
Tags
com.android.apps.tag
CQR
com.miui.qr
Gamepl
com.mi.emapal
ConfigUpdater
com.google.android.configupdater
Dynamic_System_Updates
com.android.dynsystem
debug
com.modemdebug
CatchLog
com.bsp.catchlog
com.android.emergency
com.qualcomm.qti.lpa
com.qualcomm.qti.xrcb
com.android.settings.intelligence
com.qti.qualcomm.datastatusnotification
com.qualcomm.qti.dynamicddsservice
com.miui.translation.xmcloud
com.qti.slaservice
com.qualcomm.atfwd
com.qualcomm.embms
com.qualcomm.qti.remoteSimlockAuth
com.qualcomm.qti.uim
com.qualcomm.qti.uimGbaApp
com.qualcomm.uimremoteclient
com.qualcomm.uimremoteserver
com.qti.confuridialer
com.xiaomi.shop
com.google.android.syncadapters.contacts
com.mi.health
com.miui.newmidrive
com.xiaomi.jr
com.mfashiongallery.emag
com.miui.compass
com.xiaomi.drivemode
com.duokan.reader
com.xiaomi.gamecenter
com.miui.huanji
com.miui.newhome
com.xiaomi.scanner
com.xiaomi.youpin
com.xiaomi.smarthome
com.miui.thirdappassistant
com.duokan.phone.remotecontroller
com.baidu.input_mi
com.miui.greenguard
com.miui.analytics
"

for delete_dir in $apps_dir ;do
  find $systemdir -type d -name "$delete_dir" | xargs rm -rf
done

rm -rf $1/data-app/*
